CREATE TABLE staging.enwiki_reverted_20140820 (
	rev_id                INT UNSIGNED,
	rev_timestamp         VARBINARY(14),
	rev_user              INT UNSIGNED,
	rev_user_text         VARBINARY(255),
	rev_page              INT UNSIGNED,
	rev_sha1              VARBINARY(32),
	rev_minor_edit        TINYINT,
	rev_deleted           TINYINT,
	rev_parent_id         INT UNSIGNED,
	archived              TINYINT,
	reverting_id          INT UNSIGNED,
	reverting_timestamp   VARBINARY(14),
	reverting_user        INT UNSIGNED,
	reverting_user_text   VARBINARY(255),
	reverting_page        INT UNSIGNED,
	reverting_sha1        VARBINARY(32),
	reverting_minor_edit  TINYINT,
	reverting_deleted     TINYINT,
	reverting_parent_id   INT UNSIGNED,
	reverting_archived    TINYINT,
	rev_revert_offset     INT UNSIGNED,
	revisions_reverted    INT UNSIGNED,
	reverted_to_rev_id    INT UNSIGNED
);
